version: '3.8'

services:
  trt:
    image: my-trt:10.15
    container_name: trt_dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # volumes:
      # - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash
    # 可选：限制资源
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]